### ISSUE TITLE
Function Redeclare

### ISSUE THREAD

**Issue by JPvanRooyen** [BuddyForms/BuddyForms-Post-in-Groups#3]
In testing on a local install it seems that there are Redeclare issues causing Fatal Errors.
( ! ) Fatal error: Cannot redeclare buddyforms_pig_current_user_can_edit() 
This is from /includes/functions.php line 299.

I believe it may be because that function is already called in the filter on line 276.
If this is true, most functions on this page could trigger the error.

May I suggest using a "function_exists" or "include_once" to avoide this?

Error Replication:
Have BuddyForms installed & active
Install BuddyForms-Post-in-Groups
Activate the plugin.
See Fatal Error Message.

//EDIT: 2020-04-19
Not submitting a pull request as it may need more testing, but I fixed the error by enclosing the function @ line 299 in a "if ! function exists" statement:

//added line below
if ( ! function_exists( 'buddyforms_pig_current_user_can_edit' ) ) {
function buddyforms_pig_current_user_can_edit($current_user_can){

	$settings = groups_get_groupmeta( bp_get_group_id(), '_buddyforms_pig' );

	$current_user_can =  empty( $settings['edit'] ) ? false : true;

	if ( get_the_author_meta( 'ID' ) == get_current_user_id() ) {
		$current_user_can =  true;
	}

    return $current_user_can;
	}
//added line below
}

Hope this helps :)

**Comment by rjudrok** [comment]
Same problem for me.. Fatal error: Cannot redeclare buddyforms_post_in_groups_locate_template()  \wp-content\plugins\bf-bp-post-in-groups-premium\includes\functions.php on line 20

**Comment by svenl77** [comment]
This conflicts happens if you use the github version and then try to activate the professional version. 
Please make sure to only activate one version at the time.
